### ISSUE TITLE
Uncaught ReferenceError: io is not defined

### ISSUE THREAD

**Issue by schirrel** [jdanlewis/hello-phonegap-requirejs#2]
Hi i just forked your project, i'm really interested on build phonegap with require, but i'm having this errors 

`Uncaught ReferenceError: io is not defined
    at (index):74
    at (index):109`

and
`Uncaught Error: Mismatched anonymous define() module: function () { ... `

error 404 in `cordova.js:1528 GET http://192.168.0.108:3000/cordova_plugins.js `

and 
```

[phonegap] 200 /main.min.js
TypeError: Path must be a string. Received undefined
    at assertPath (path.js:8:11)
    at Object.win32.join (path.js:221:5)
    at Object.handle (C:\Users\AppData\Roaming\npm\node_modules\phonegap\node_modules\connect-phonegap\lib\middleware\cordova\cordova_plugins.js:18:33)
    at next (C:\Users\AppData\Roaming\npm\node_modules\phonegap\node_modules\connect-phonegap\node_modules\connect\lib\proto.js:174:15)
    at Object.handle (C:\Users\AppData\Roaming\npm\node_modules\phonegap\node_modules\connect-phonegap\lib\middleware\cordova\cordova.js:33:13)
    at next (C:\Users\AppData\Roaming\npm\node_modules\phonegap\node_modules\connect-phonegap\node_modules\connect\lib\proto.js:174:15)
    at SendStream.error (C:\Users\AppData\Roaming\npm\node_modules\phonegap\node_modules\connect-phonegap\node_modules\connect\node_modules\serve-static\index.js:120:7)
    at emitOne (events.js:77:13)
    at SendStream.emit (events.js:169:7)
    at SendStream.error (C:\Users\AppData\Roaming\npm\node_modules\phonegap\node_modules\connect-phonegap\node_modules\connect\node_modules\serve-static\node_modules\send\index.js:245:17)
[phonegap] 500 /cordova_plugins.js

```
at the console.
i followed all your steps, did i miss something else?

**Comment by jdanlewis** [comment]
Hello,

This project is quite old and most of its dependencies are likely several major versions behind. I'll update the README in this repo to clarify this project is unmaintained.

PhoneGap has come a long way. Check out http://phonegap.com/getstarted.

Good luck!
